apiVersion: kuscia.secretflow/v1alpha1
kind: AppImage
metadata:
  annotations:
    kuscia.secretflow/component-spec: '{"component.1.description":"ecdh","component.1.input.1.categories":"dataset","component.1.input.1.description":"train data","component.1.input.1.name":"train_data","component.1.name":"ic-ecdh","component.1.output.1.categories":"dataset","component.1.output.1.description":"train data","component.1.output.1.name":"train_data","component.1.output.2.categories":"report","component.1.output.2.description":"summary","component.1.output.2.name":"summary"}'
  name: ic-ecdh
spec:
  deployTemplates:
  - name: ss-lr
    replicas: 1
    spec:
      containers:
      - name: ss-lr
        workingDir: /work
  image:
    name: secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/morse-ecdh-header
    tag: "20251113"
